name: futebol
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  sqflite: ^2.0.3+1
  path:
  flutter_triple:
  flutter_modular:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail:
  faker: ^2.0.0

  flutter_lints: ^2.0.0

flutter:
  assets: 
    - images/flags/

  uses-material-design: true